title: EMF Solar System
description: A solar system created by attendees of Electromagnetic Field 2026.

theme: just-the-docs
url: https://elichad.github.io/community-blanket/
aux_links:
  GitHub: https://github.com/elichad/community-blanket/

# url: https://elichad.github.io
# baseurl: /community-blanket

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "2026"
  - scope:
      path: "pages/2024/" # an empty string here means all files in the project
    values:
      layout: "2024"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
